---

# Copy the cli binaries to Nginx directory

- local_action: stat path={{ openwhisk_cli.local.location }}/{{ item }}
  register: binary_path

- name: "ensure Nginx cli directory is writable"
  file:
    path: "{{ cli.nginxdir }}"
    state: directory
    mode: 0777
  become: "{{ cli.dir.become }}"

- name: "copy the local binaries from a local directory to Nginx directory"
  copy: src={{ openwhisk_cli.local.location }}/{{ item }} dest={{ cli.nginxdir }}/
  when: binary_path.stat.exists
