---
# This role will deploy a database server. Use the role if you want to use CouchCB locally.
# In deploy mode it will start the CouchDB container.
# In clean mode it will remove the CouchDB container.

- include: deploy.yml
  when: mode == "deploy"

- include: clean.yml
  when: mode == "clean"
