/*
 * OpenWhisk REST API
 * API for OpenWhisk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ActivationInfoResult;
import java.io.IOException;

/**
 * ActivationInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-24T21:18:05.110+07:00")
public class ActivationInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("result")
  private ActivationInfoResult result = null;

  @SerializedName("stdout")
  private String stdout = null;

  @SerializedName("stderr")
  private String stderr = null;

  public ActivationInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Activation id
   * @return id
  **/
  @ApiModelProperty(value = "Activation id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActivationInfo result(ActivationInfoResult result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public ActivationInfoResult getResult() {
    return result;
  }

  public void setResult(ActivationInfoResult result) {
    this.result = result;
  }

  public ActivationInfo stdout(String stdout) {
    this.stdout = stdout;
    return this;
  }

   /**
   * Standard output from activation
   * @return stdout
  **/
  @ApiModelProperty(value = "Standard output from activation")
  public String getStdout() {
    return stdout;
  }

  public void setStdout(String stdout) {
    this.stdout = stdout;
  }

  public ActivationInfo stderr(String stderr) {
    this.stderr = stderr;
    return this;
  }

   /**
   * Standard error from activation
   * @return stderr
  **/
  @ApiModelProperty(value = "Standard error from activation")
  public String getStderr() {
    return stderr;
  }

  public void setStderr(String stderr) {
    this.stderr = stderr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivationInfo activationInfo = (ActivationInfo) o;
    return Objects.equals(this.id, activationInfo.id) &&
        Objects.equals(this.result, activationInfo.result) &&
        Objects.equals(this.stdout, activationInfo.stdout) &&
        Objects.equals(this.stderr, activationInfo.stderr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, result, stdout, stderr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivationInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    stdout: ").append(toIndentedString(stdout)).append("\n");
    sb.append("    stderr: ").append(toIndentedString(stderr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

