---
# This role will install apigateway in the group 'apigateway' in the environment inventory
# In deploy mode it will deploy apigateway.
# In clean mode it will remove the apigateway containers.

- include: deploy.yml
  when: mode == "deploy"

- include: clean.yml
  when: mode == "clean"

