---
# This role will install Kafka with Zookeeper in group 'kafka' in the environment inventory

- name: "pull the zookeeper:{{ zookeeper.version }} image"
  shell: "docker pull zookeeper:{{ zookeeper.version }}"
  retries: "{{ docker.pull.retries }}"
  delay: "{{ docker.pull.delay }}"

- name: (re)start zookeeper
  docker_container:
    name: zookeeper
    image: zookeeper:{{ zookeeper.version }}
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    ports:
      - "{{ zookeeper.port }}:2181"

- name: wait until the Zookeeper in this host is up and running
  action: shell (echo ruok; sleep 1) | nc {{ ansible_host }} {{ zookeeper.port }}
  register: result
  until: (result.rc == 0) and (result.stdout == 'imok')
  retries: 36
  delay: 5

- name: "pull the ches/kafka:{{ kafka.version }} image"
  shell: "docker pull ches/kafka:{{ kafka.version }}"
  retries: "{{ docker.pull.retries }}"
  delay: "{{ docker.pull.delay }}"

- name: (re)start kafka
  docker_container:
    name: kafka
    image: ches/kafka:{{ kafka.version }}
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    links:
      - "zookeeper:zookeeper"
    env:
      "KAFKA_ADVERTISED_HOST_NAME": "{{ ansible_host }}"
      "KAFKA_HEAP_OPTS": "-Xmx{{ kafka.heap }} -Xms{{ kafka.heap }}"
    ports:
      - "{{ kafka.port }}:9092"

- name: wait until the kafka server started up
  shell: docker logs kafka
  register: result
  until: ('[Kafka Server 0], started' in result.stdout)
  retries: 10
  delay: 5

- name: create the health and the cacheInvalidation topic
  shell: "docker exec kafka bash -c 'unset JMX_PORT; kafka-topics.sh --create --topic {{ item.name }} --replication-factor 1 --partitions 1 --zookeeper {{ ansible_host }}:{{ zookeeper.port }} --config retention.bytes={{ item.settings.retentionBytes }} --config retention.ms={{ item.settings.retentionMS }} --config segment.bytes={{ item.settings.segmentBytes }}'"
  register: command_result
  failed_when: "not ('Created topic' in command_result.stdout or 'already exists' in command_result.stdout)"
  changed_when: "'Created topic' in command_result.stdout"
  with_items:
  - name: health
    settings: "{{ kafka.topics.health }}"
  - name: cacheInvalidation
    settings: "{{ kafka.topics.cacheInvalidation }}"
