/*
 * OpenWhisk REST API
 * API for OpenWhisk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ActivationResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-28T00:15:16.400+07:00")
public class ActivationResponse {
  @SerializedName("result")
  private Object result = null;

  @SerializedName("success")
  private Boolean success = null;

  @SerializedName("status")
  private String status = null;

  public ActivationResponse result(Object result) {
    this.result = result;
    return this;
  }

   /**
   * Any JSON value
   * @return result
  **/
  @ApiModelProperty(value = "Any JSON value")
  public Object getResult() {
    return result;
  }

  public void setResult(Object result) {
    this.result = result;
  }

  public ActivationResponse success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * Indicates whether the activation was successful
   * @return success
  **/
  @ApiModelProperty(value = "Indicates whether the activation was successful")
  public Boolean getSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public ActivationResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Exit status of the activation
   * @return status
  **/
  @ApiModelProperty(value = "Exit status of the activation")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivationResponse activationResponse = (ActivationResponse) o;
    return Objects.equals(this.result, activationResponse.result) &&
        Objects.equals(this.success, activationResponse.success) &&
        Objects.equals(this.status, activationResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, success, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivationResponse {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

