/* GENERATED BY TYPECHAIN VER. 0.1.2 */
/* tslint:disable */

import { BigNumber } from "bignumber.js";
import {
  TypeChainContract,
  promisify,
  ITxParams,
  IPayableTxParams,
  DeferredTransactionWrapper
} from "./typechain-runtime";

export class Registration extends TypeChainContract {
  public readonly rawWeb3Contract: any;

  public constructor(web3: any, address: string | BigNumber) {
    const abi = [
      {
        constant: true,
        inputs: [],
        name: "bank",
        outputs: [{ name: "", type: "bytes32" }],
        payable: false,
        type: "function"
      },
      {
        constant: true,
        inputs: [],
        name: "accNo",
        outputs: [{ name: "", type: "bytes32" }],
        payable: false,
        type: "function"
      },
      {
        constant: true,
        inputs: [],
        name: "telNo",
        outputs: [{ name: "", type: "bytes32" }],
        payable: false,
        type: "function"
      },
      {
        inputs: [
          { name: "_telNo", type: "string" },
          { name: "_bank", type: "string" },
          { name: "_accNo", type: "string" }
        ],
        payable: false,
        type: "constructor"
      }
    ];
    super(web3, address, abi);
  }

  static async createAndValidate(
    web3: any,
    address: string | BigNumber
  ): Promise<Registration> {
    const contract = new Registration(web3, address);
    const code = await promisify(web3.eth.getCode, [address]);
    if (code === "0x0") {
      throw new Error(`Contract at ${address} doesn't exist!`);
    }
    return contract;
  }

  public get bank(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.bank, []);
  }
  public get accNo(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.accNo, []);
  }
  public get telNo(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.telNo, []);
  }
}
