/* GENERATED BY TYPECHAIN VER. 0.1.2 */
/* tslint:disable */

import { BigNumber } from "bignumber.js";
import {
  TypeChainContract,
  promisify,
  ITxParams,
  IPayableTxParams,
  DeferredTransactionWrapper
} from "./typechain-runtime";

export class TransferState extends TypeChainContract {
  public readonly rawWeb3Contract: any;

  public constructor(web3: any, address: string | BigNumber) {
    const abi = [
      {
        constant: true,
        inputs: [],
        name: "currentState",
        outputs: [{ name: "", type: "uint8" }],
        payable: false,
        type: "function"
      },
      {
        constant: false,
        inputs: [],
        name: "complete",
        outputs: [],
        payable: false,
        type: "function"
      },
      {
        constant: false,
        inputs: [],
        name: "start",
        outputs: [],
        payable: false,
        type: "function"
      },
      {
        constant: false,
        inputs: [],
        name: "pending",
        outputs: [],
        payable: false,
        type: "function"
      },
      {
        inputs: [{ name: "_txId", type: "string" }],
        payable: false,
        type: "constructor"
      }
    ];
    super(web3, address, abi);
  }

  static async createAndValidate(
    web3: any,
    address: string | BigNumber
  ): Promise<TransferState> {
    const contract = new TransferState(web3, address);
    const code = await promisify(web3.eth.getCode, [address]);
    if (code === "0x0") {
      throw new Error(`Contract at ${address} doesn't exist!`);
    }
    return contract;
  }

  public get currentState(): Promise<BigNumber> {
    return promisify(this.rawWeb3Contract.currentState, []);
  }

  public completeTx(): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, "complete", []);
  }
  public startTx(): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, "start", []);
  }
  public pendingTx(): DeferredTransactionWrapper<ITxParams> {
    return new DeferredTransactionWrapper<ITxParams>(this, "pending", []);
  }
}
