---
# This role will install Docker using apt.

- name: add docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    update_cache: yes
    state: present
  become: true

- name: install docker
  apt:
    name: "docker-engine={{ docker.version }}"
    state: present
    force: yes
  become: true

- name: configure docker
  template:
    src: docker.j2
    dest: "/etc/default/docker"
  become: true

- name: add user to docker group
  user:
    name: "{{docker.user|default(ansible_user_id)}}"
    groups: docker
    append: true
  become: true

- name: restart docker service
  service:
    name: docker
    state: restarted
  become: true
