---
# This role will install controller in group 'controllers' in the environment inventory
# In deploy mode it will deploy controllers.
# In clean mode it will remove the controller containers.

- include: deploy.yml
  when: mode == "deploy"

- include: clean.yml
  when: mode == "clean"