/*
 * OpenWhisk REST API
 * API for OpenWhisk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.EntityBrief;
import io.swagger.client.model.ErrorMessage;
import io.swagger.client.model.ItemId;
import io.swagger.client.model.ModelPackage;
import io.swagger.client.model.PackagePut;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PackagesApi
 */
@Ignore
public class PackagesApiTest {

    private final PackagesApi api = new PackagesApi();

    
    /**
     * Delete a package
     *
     * Delete a package
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletePackageTest() throws ApiException {
        String namespace = null;
        String packageName = null;
        api.deletePackage(namespace, packageName);

        // TODO: test validations
    }
    
    /**
     * Get all packages
     *
     * Get all packages
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAlPackagesTest() throws ApiException {
        String namespace = null;
        Boolean _public = null;
        Integer limit = null;
        Integer skip = null;
        List<EntityBrief> response = api.getAlPackages(namespace, _public, limit, skip);

        // TODO: test validations
    }
    
    /**
     * Get package information
     *
     * Get package information.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPackageByNameTest() throws ApiException {
        String namespace = null;
        String packageName = null;
        ModelPackage response = api.getPackageByName(namespace, packageName);

        // TODO: test validations
    }
    
    /**
     * Create or update a package
     *
     * Create or update a package
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePackageTest() throws ApiException {
        String namespace = null;
        String packageName = null;
        PackagePut _package = null;
        String overwrite = null;
        ItemId response = api.updatePackage(namespace, packageName, _package, overwrite);

        // TODO: test validations
    }
    
}
